const data = [
  {
    fullName: "Haze Keable",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Gujarati",
    ssn: "869-50-5709",
    money: "$515.60",
  },
  {
    fullName: "Marybeth Pays",
    gender: "Female",
    jobTitle: "Database Administrator IV",
    language: "Malagasy",
    ssn: "646-78-9615",
    money: "$655.13",
  },
  {
    fullName: "Ruthie Game",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Thai",
    ssn: "472-39-2588",
    money: "$387.19",
  },
  {
    fullName: "Emmeline Rustan",
    gender: "Female",
    jobTitle: "Statistician IV",
    language: "Aymara",
    ssn: "185-61-3766",
    money: "$871.45",
  },
  {
    fullName: "Alain Coolahan",
    gender: "Male",
    jobTitle: "Marketing Manager",
    language: "Assamese",
    ssn: "376-24-5012",
    money: "$871.11",
  },
  {
    fullName: "Winnah Domenge",
    gender: "Female",
    jobTitle: "Accounting Assistant II",
    language: "Khmer",
    ssn: "718-39-7926",
    money: "$411.26",
  },
  {
    fullName: "Miles Barnett",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Sotho",
    ssn: "389-32-4465",
    money: "$186.81",
  },
  {
    fullName: "Kiel Goodsall",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Kannada",
    ssn: "384-34-4854",
    money: "$259.89",
  },
  {
    fullName: "Ardelia Crichton",
    gender: "Female",
    jobTitle: "Web Developer I",
    language: "Italian",
    ssn: "606-06-9859",
    money: "$548.59",
  },
  {
    fullName: "Chadd Vile",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "New Zealand Sign Language",
    ssn: "403-75-8820",
    money: "$571.76",
  },
  {
    fullName: "Gibb Penman",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Yiddish",
    ssn: "230-45-9578",
    money: "$59.42",
  },
  {
    fullName: "Trina Tubb",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Thai",
    ssn: "510-69-0582",
    money: "$220.45",
  },
  {
    fullName: "Bessy Lancashire",
    gender: "Female",
    jobTitle: "Software Engineer IV",
    language: "Belarusian",
    ssn: "222-97-7189",
    money: "$72.34",
  },
  {
    fullName: "Maggie Lygo",
    gender: "Female",
    jobTitle: "Electrical Engineer",
    language: "Gujarati",
    ssn: "153-02-3835",
    money: "$273.45",
  },
  {
    fullName: "Reese Castilljo",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "Finnish",
    ssn: "297-36-7587",
    money: "$108.65",
  },
  {
    fullName: "Salvidor Hinzer",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Spanish",
    ssn: "819-59-7383",
    money: "$747.42",
  },
  {
    fullName: "Adam Coverley",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Swahili",
    ssn: "698-60-5504",
    money: "$639.11",
  },
  {
    fullName: "Dottie Bardwell",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Catalan",
    ssn: "808-53-7432",
    money: "$260.62",
  },
  {
    fullName: "Maxy McPhilip",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Korean",
    ssn: "779-26-2808",
    money: "$126.07",
  },
  {
    fullName: "Gina Major",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Dzongkha",
    ssn: "488-31-2287",
    money: "$219.12",
  },
  {
    fullName: "Zenia Di Boldi",
    gender: "Female",
    jobTitle: "Recruiting Manager",
    language: "Afrikaans",
    ssn: "599-62-7155",
    money: "$691.48",
  },
  {
    fullName: "Nial Whittingham",
    gender: "Male",
    jobTitle: "Safety Technician I",
    language: "Gujarati",
    ssn: "507-57-8307",
    money: "$92.99",
  },
  {
    fullName: "Ingrid Cumpsty",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Lithuanian",
    ssn: "641-70-1768",
    money: "$620.95",
  },
  {
    fullName: "Gaylor Tissell",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Quechua",
    ssn: "847-90-7417",
    money: "$741.62",
  },
  {
    fullName: "Marie-jeanne O'Brogan",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Filipino",
    ssn: "582-26-3103",
    money: "$719.13",
  },
  {
    fullName: "Law Vatini",
    gender: "Male",
    jobTitle: "Safety Technician IV",
    language: "Khmer",
    ssn: "169-25-0401",
    money: "$538.10",
  },
  {
    fullName: "Caitlin Klosges",
    gender: "Female",
    jobTitle: "Research Assistant III",
    language: "Persian",
    ssn: "427-13-6328",
    money: "$550.02",
  },
  {
    fullName: "Randene Nibloe",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Malayalam",
    ssn: "319-46-2707",
    money: "$890.96",
  },
  {
    fullName: "Zebulon Hullett",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Norwegian",
    ssn: "109-38-0042",
    money: "$807.19",
  },
  {
    fullName: "Ernestine Ridings",
    gender: "Female",
    jobTitle: "Research Assistant I",
    language: "Korean",
    ssn: "714-35-4057",
    money: "$997.71",
  },
  {
    fullName: "Berkley Lumsden",
    gender: "Male",
    jobTitle: "Office Assistant III",
    language: "Korean",
    ssn: "447-48-8847",
    money: "$861.87",
  },
  {
    fullName: "Torey Barczynski",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Yiddish",
    ssn: "295-79-8328",
    money: "$891.83",
  },
  {
    fullName: "Madge Britten",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Gujarati",
    ssn: "428-87-7471",
    money: "$682.65",
  },
  {
    fullName: "Florie Medley",
    gender: "Female",
    jobTitle: "Editor",
    language: "Zulu",
    ssn: "567-48-9162",
    money: "$165.22",
  },
  {
    fullName: "Nadiya Schulken",
    gender: "Female",
    jobTitle: "Web Designer IV",
    language: "Ndebele",
    ssn: "381-84-2734",
    money: "$141.39",
  },
  {
    fullName: "Ania Titford",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Afrikaans",
    ssn: "591-37-6650",
    money: "$826.45",
  },
  {
    fullName: "Silvanus Koba",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Romanian",
    ssn: "383-62-2339",
    money: "$392.47",
  },
  {
    fullName: "Valida Tithecote",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Swati",
    ssn: "161-91-1217",
    money: "$399.67",
  },
  {
    fullName: "Auria Wollers",
    gender: "Female",
    jobTitle: "Sales Representative",
    language: "Norwegian",
    ssn: "608-70-5891",
    money: "$854.43",
  },
  {
    fullName: "Myranda Broadwell",
    gender: "Female",
    jobTitle: "Media Manager IV",
    language: "Kurdish",
    ssn: "585-68-3093",
    money: "$339.95",
  },
  {
    fullName: "Rudy Erington",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Indonesian",
    ssn: "637-47-7191",
    money: "$289.37",
  },
  {
    fullName: "Steffie Wilsey",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Swedish",
    ssn: "466-78-3684",
    money: "$266.21",
  },
  {
    fullName: "Sophi Botler",
    gender: "Female",
    jobTitle: "Accountant IV",
    language: "Belarusian",
    ssn: "416-72-9254",
    money: "$706.73",
  },
  {
    fullName: "Tobe Pedroni",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Hiri Motu",
    ssn: "410-74-9502",
    money: "$228.29",
  },
  {
    fullName: "Lothario Bolding",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst III",
    language: "Italian",
    ssn: "399-77-4806",
    money: "$925.35",
  },
  {
    fullName: "Jens Puckrin",
    gender: "Male",
    jobTitle: "Human Resources Assistant IV",
    language: "Swati",
    ssn: "401-15-9898",
    money: "$944.56",
  },
  {
    fullName: "Kinsley Beavington",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Tsonga",
    ssn: "598-71-3390",
    money: "$13.61",
  },
  {
    fullName: "Care Massey",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "West Frisian",
    ssn: "590-63-6207",
    money: "$893.07",
  },
  {
    fullName: "Lion Kiossel",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Portuguese",
    ssn: "150-88-0584",
    money: "$815.02",
  },
  {
    fullName: "Bartram Bleythin",
    gender: "Male",
    jobTitle: "Assistant Media Planner",
    language: "Nepali",
    ssn: "620-21-9652",
    money: "$684.48",
  },
  {
    fullName: "Jedidiah Tiptaft",
    gender: "Male",
    jobTitle: "Biostatistician I",
    language: "Spanish",
    ssn: "715-58-8185",
    money: "$814.68",
  },
  {
    fullName: "Meade Yven",
    gender: "Male",
    jobTitle: "Statistician IV",
    language: "Filipino",
    ssn: "342-79-3083",
    money: "$861.27",
  },
  {
    fullName: "Clea Whaley",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Bengali",
    ssn: "793-92-7921",
    money: "$806.53",
  },
  {
    fullName: "Cozmo Mitskevich",
    gender: "Male",
    jobTitle: "VP Accounting",
    language: "Arabic",
    ssn: "717-65-5418",
    money: "$626.22",
  },
  {
    fullName: "Angelika Brame",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Oriya",
    ssn: "678-54-8706",
    money: "$951.37",
  },
  {
    fullName: "Tomkin Coen",
    gender: "Male",
    jobTitle: "Editor",
    language: "Croatian",
    ssn: "806-23-0115",
    money: "$504.27",
  },
  {
    fullName: "Jenilee Clausen-Thue",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "Albanian",
    ssn: "120-49-0113",
    money: "$614.47",
  },
  {
    fullName: "Chuck Clawley",
    gender: "Male",
    jobTitle: "Help Desk Technician",
    language: "Dzongkha",
    ssn: "600-51-1163",
    money: "$67.27",
  },
  {
    fullName: "Chloe Waplington",
    gender: "Female",
    jobTitle: "Administrative Officer",
    language: "Gagauz",
    ssn: "266-42-7382",
    money: "$448.34",
  },
  {
    fullName: "Alameda Bagg",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Punjabi",
    ssn: "507-32-1216",
    money: "$907.13",
  },
  {
    fullName: "Catha Skule",
    gender: "Female",
    jobTitle: "Statistician II",
    language: "Hebrew",
    ssn: "514-01-8410",
    money: "$820.83",
  },
  {
    fullName: "Zedekiah Aslie",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Khmer",
    ssn: "358-45-1751",
    money: "$217.71",
  },
  {
    fullName: "Coral Mieville",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Nepali",
    ssn: "761-36-7510",
    money: "$673.63",
  },
  {
    fullName: "Mira Stichall",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Maltese",
    ssn: "656-07-8784",
    money: "$997.39",
  },
  {
    fullName: "Suellen Livingston",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Mongolian",
    ssn: "684-97-9531",
    money: "$959.43",
  },
  {
    fullName: "Merl Kingerby",
    gender: "Female",
    jobTitle: "Data Coordinator",
    language: "Dutch",
    ssn: "571-49-9655",
    money: "$582.78",
  },
  {
    fullName: "Kerrin Gouge",
    gender: "Female",
    jobTitle: "Research Assistant I",
    language: "Kashmiri",
    ssn: "579-26-3502",
    money: "$44.86",
  },
  {
    fullName: "Charmane Radbourn",
    gender: "Female",
    jobTitle: "Marketing Manager",
    language: "Portuguese",
    ssn: "865-56-1822",
    money: "$544.89",
  },
  {
    fullName: "Philipa Spadazzi",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Montenegrin",
    ssn: "794-97-7459",
    money: "$861.04",
  },
  {
    fullName: "Gallard Mephan",
    gender: "Male",
    jobTitle: "Librarian",
    language: "Lithuanian",
    ssn: "885-39-5594",
    money: "$951.35",
  },
  {
    fullName: "Keefer Lepick",
    gender: "Male",
    jobTitle: "Software Test Engineer I",
    language: "Spanish",
    ssn: "331-31-0530",
    money: "$353.27",
  },
  {
    fullName: "Heida Shann",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Croatian",
    ssn: "775-91-8108",
    money: "$952.32",
  },
  {
    fullName: "Sonnnie Beeze",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Amharic",
    ssn: "432-36-9522",
    money: "$159.13",
  },
  {
    fullName: "Bunny Dagless",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Belarusian",
    ssn: "268-91-7258",
    money: "$291.43",
  },
  {
    fullName: "Tully Mussett",
    gender: "Male",
    jobTitle: "Account Representative II",
    language: "Dari",
    ssn: "362-02-8752",
    money: "$51.81",
  },
  {
    fullName: "Fanchon Skokoe",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Greek",
    ssn: "785-25-6555",
    money: "$884.49",
  },
  {
    fullName: "Bartholemy Ashplant",
    gender: "Male",
    jobTitle: "VP Accounting",
    language: "Afrikaans",
    ssn: "284-43-6315",
    money: "$36.00",
  },
  {
    fullName: "Junette Hannigane",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "English",
    ssn: "352-07-5128",
    money: "$968.84",
  },
  {
    fullName: "Page Haslewood",
    gender: "Female",
    jobTitle: "Computer Systems Analyst IV",
    language: "Chinese",
    ssn: "374-25-9207",
    money: "$501.54",
  },
  {
    fullName: "Lydon Pleasaunce",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Georgian",
    ssn: "104-66-7686",
    money: "$509.46",
  },
  {
    fullName: "Antin McWilliam",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Persian",
    ssn: "495-78-0700",
    money: "$549.12",
  },
  {
    fullName: "Aryn Haythorne",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Finnish",
    ssn: "258-15-4052",
    money: "$567.03",
  },
  {
    fullName: "Nickie Denizet",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Chinese",
    ssn: "228-33-6645",
    money: "$887.50",
  },
  {
    fullName: "Virgina Tiesman",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Belarusian",
    ssn: "260-89-1020",
    money: "$163.95",
  },
  {
    fullName: "Lanna Burl",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Marathi",
    ssn: "429-19-3240",
    money: "$935.42",
  },
  {
    fullName: "Cindie Smout",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Catalan",
    ssn: "846-17-9741",
    money: "$681.97",
  },
  {
    fullName: "Fianna Croshaw",
    gender: "Female",
    jobTitle: "Computer Systems Analyst III",
    language: "Fijian",
    ssn: "242-19-5457",
    money: "$259.37",
  },
  {
    fullName: "Foss Grimsdith",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Catalan",
    ssn: "882-92-4099",
    money: "$277.41",
  },
  {
    fullName: "Worthington Yusupov",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Latvian",
    ssn: "100-67-4399",
    money: "$334.64",
  },
  {
    fullName: "Jilleen Fazakerley",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Kazakh",
    ssn: "869-10-3593",
    money: "$279.19",
  },
  {
    fullName: "Dare Levy",
    gender: "Male",
    jobTitle: "Automation Specialist IV",
    language: "Georgian",
    ssn: "444-90-5807",
    money: "$862.72",
  },
  {
    fullName: "Graeme Reavell",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Kazakh",
    ssn: "224-02-9513",
    money: "$343.71",
  },
  {
    fullName: "Delinda Enston",
    gender: "Female",
    jobTitle: "Senior Editor",
    language: "Norwegian",
    ssn: "802-55-4538",
    money: "$101.68",
  },
  {
    fullName: "Maritsa Blaxton",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Quechua",
    ssn: "236-94-5088",
    money: "$948.40",
  },
  {
    fullName: "Jaine Toby",
    gender: "Female",
    jobTitle: "Chemical Engineer",
    language: "Bengali",
    ssn: "454-25-5239",
    money: "$789.13",
  },
  {
    fullName: "Engelbert Craighill",
    gender: "Male",
    jobTitle: "Recruiter",
    language: "Japanese",
    ssn: "746-29-8670",
    money: "$210.83",
  },
  {
    fullName: "Bertie Guiot",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Thai",
    ssn: "795-36-5162",
    money: "$834.69",
  },
  {
    fullName: "Ulrica Kimmons",
    gender: "Female",
    jobTitle: "Quality Control Specialist",
    language: "Malayalam",
    ssn: "557-27-2638",
    money: "$24.94",
  },
  {
    fullName: "Ari Soanes",
    gender: "Male",
    jobTitle: "Web Designer I",
    language: "Khmer",
    ssn: "687-98-1020",
    money: "$830.63",
  },
  {
    fullName: "Cornelle Putton",
    gender: "Female",
    jobTitle: "Nuclear Power Engineer",
    language: "Tswana",
    ssn: "500-64-5647",
    money: "$901.20",
  },
  {
    fullName: "Shepard Leagas",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Czech",
    ssn: "690-74-8602",
    money: "$602.46",
  },
  {
    fullName: "Arnie Vassar",
    gender: "Male",
    jobTitle: "Professor",
    language: "Punjabi",
    ssn: "559-17-0894",
    money: "$767.54",
  },
  {
    fullName: "Hamish Korda",
    gender: "Male",
    jobTitle: "Systems Administrator II",
    language: "Tetum",
    ssn: "767-33-2966",
    money: "$441.96",
  },
  {
    fullName: "Valenka Sarchwell",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Dhivehi",
    ssn: "609-90-7176",
    money: "$614.34",
  },
  {
    fullName: "Kirsten Gwynne",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "West Frisian",
    ssn: "526-01-0049",
    money: "$61.37",
  },
  {
    fullName: "Kellen Elmar",
    gender: "Female",
    jobTitle: "Safety Technician III",
    language: "Haitian Creole",
    ssn: "171-32-2552",
    money: "$501.85",
  },
  {
    fullName: "Jammie Ravilious",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Sotho",
    ssn: "637-32-9861",
    money: "$708.80",
  },
  {
    fullName: "Courtnay Broose",
    gender: "Female",
    jobTitle: "Geologist IV",
    language: "Tetum",
    ssn: "132-35-2014",
    money: "$76.42",
  },
  {
    fullName: "Desdemona Gylle",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Norwegian",
    ssn: "377-20-4312",
    money: "$103.89",
  },
  {
    fullName: "Zebulen Maile",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Malayalam",
    ssn: "459-27-9686",
    money: "$636.35",
  },
  {
    fullName: "Padriac Bonwell",
    gender: "Male",
    jobTitle: "Programmer II",
    language: "Haitian Creole",
    ssn: "761-24-5671",
    money: "$77.92",
  },
  {
    fullName: "Theo Harrop",
    gender: "Male",
    jobTitle: "Editor",
    language: "Finnish",
    ssn: "186-74-9205",
    money: "$979.82",
  },
  {
    fullName: "Sydelle Kalinke",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Chinese",
    ssn: "334-61-5879",
    money: "$163.53",
  },
  {
    fullName: "Mariska Gehrels",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Ndebele",
    ssn: "805-26-4802",
    money: "$962.26",
  },
  {
    fullName: "Blaire McKeighan",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Fijian",
    ssn: "226-11-4215",
    money: "$516.92",
  },
  {
    fullName: "Konrad McAllan",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Tetum",
    ssn: "461-81-7529",
    money: "$416.13",
  },
  {
    fullName: "Sandro Pinshon",
    gender: "Male",
    jobTitle: "Automation Specialist III",
    language: "Swahili",
    ssn: "641-42-4533",
    money: "$580.99",
  },
  {
    fullName: "Sella Tanton",
    gender: "Female",
    jobTitle: "Accountant III",
    language: "Danish",
    ssn: "477-52-3220",
    money: "$568.24",
  },
  {
    fullName: "Daniel Garraway",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Finnish",
    ssn: "181-53-3521",
    money: "$86.67",
  },
  {
    fullName: "Evelyn Margaritelli",
    gender: "Male",
    jobTitle: "Web Designer II",
    language: "Thai",
    ssn: "515-92-4486",
    money: "$686.73",
  },
  {
    fullName: "Jocko Ginnelly",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Bengali",
    ssn: "467-43-0001",
    money: "$930.63",
  },
  {
    fullName: "Neysa Wendover",
    gender: "Female",
    jobTitle: "Administrative Assistant IV",
    language: "Korean",
    ssn: "217-30-2082",
    money: "$522.89",
  },
  {
    fullName: "Burtie Dagnall",
    gender: "Male",
    jobTitle: "Geologist II",
    language: "Albanian",
    ssn: "276-15-9319",
    money: "$263.90",
  },
  {
    fullName: "Katusha Chew",
    gender: "Female",
    jobTitle: "Administrative Assistant III",
    language: "Kyrgyz",
    ssn: "560-50-2343",
    money: "$674.81",
  },
  {
    fullName: "Alano McClymont",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Azeri",
    ssn: "514-83-0742",
    money: "$132.75",
  },
  {
    fullName: "Borg Phythien",
    gender: "Male",
    jobTitle: "Administrative Assistant IV",
    language: "Burmese",
    ssn: "792-93-2340",
    money: "$275.24",
  },
  {
    fullName: "Alex Siveyer",
    gender: "Male",
    jobTitle: "Editor",
    language: "Indonesian",
    ssn: "357-95-4477",
    money: "$381.93",
  },
  {
    fullName: "Dante Littrik",
    gender: "Male",
    jobTitle: "Research Associate",
    language: "Chinese",
    ssn: "771-14-4360",
    money: "$118.59",
  },
  {
    fullName: "Boothe Pickvance",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Hiri Motu",
    ssn: "775-02-1997",
    money: "$183.29",
  },
  {
    fullName: "Sigfrid Thying",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Norwegian",
    ssn: "495-45-7926",
    money: "$690.42",
  },
  {
    fullName: "Batsheva Sima",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Belarusian",
    ssn: "760-48-8790",
    money: "$958.14",
  },
  {
    fullName: "Winni Lofthouse",
    gender: "Female",
    jobTitle: "Web Designer III",
    language: "Chinese",
    ssn: "109-29-8098",
    money: "$214.60",
  },
  {
    fullName: "Nikaniki Somerton",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Arabic",
    ssn: "395-49-8511",
    money: "$904.74",
  },
  {
    fullName: "Blakelee Blackhall",
    gender: "Female",
    jobTitle: "Electrical Engineer",
    language: "Danish",
    ssn: "243-42-7623",
    money: "$411.20",
  },
  {
    fullName: "Lisette Thorndale",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Hungarian",
    ssn: "185-49-7728",
    money: "$963.23",
  },
  {
    fullName: "Johnath Ody",
    gender: "Female",
    jobTitle: "VP Quality Control",
    language: "Italian",
    ssn: "457-60-7030",
    money: "$117.50",
  },
  {
    fullName: "Rahel Charpling",
    gender: "Female",
    jobTitle: "Design Engineer",
    language: "Arabic",
    ssn: "742-06-1030",
    money: "$548.14",
  },
  {
    fullName: "Garner Frizzell",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Estonian",
    ssn: "155-24-6748",
    money: "$137.28",
  },
  {
    fullName: "Cam Cleife",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Persian",
    ssn: "105-64-9282",
    money: "$841.64",
  },
  {
    fullName: "Milissent Bunt",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "French",
    ssn: "382-85-4293",
    money: "$773.30",
  },
  {
    fullName: "Norris Goulder",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Sotho",
    ssn: "495-32-4034",
    money: "$396.72",
  },
  {
    fullName: "Corbet Engel",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "Telugu",
    ssn: "624-98-8118",
    money: "$195.49",
  },
  {
    fullName: "Alanna Simpson",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Latvian",
    ssn: "847-07-3682",
    money: "$175.26",
  },
  {
    fullName: "Neilla Brownsey",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Yiddish",
    ssn: "424-25-4789",
    money: "$219.99",
  },
  {
    fullName: "Brent Blackeby",
    gender: "Male",
    jobTitle: "Staff Accountant I",
    language: "Oriya",
    ssn: "132-38-3905",
    money: "$127.07",
  },
  {
    fullName: "Vivie Seery",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "Oriya",
    ssn: "167-99-6472",
    money: "$958.01",
  },
  {
    fullName: "Elena Martusov",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Kyrgyz",
    ssn: "520-44-4319",
    money: "$612.49",
  },
  {
    fullName: "Isaiah Barthot",
    gender: "Male",
    jobTitle: "Geologist III",
    language: "Māori",
    ssn: "596-20-8734",
    money: "$807.26",
  },
  {
    fullName: "Susanetta Jump",
    gender: "Female",
    jobTitle: "Human Resources Assistant IV",
    language: "Italian",
    ssn: "857-44-3522",
    money: "$262.13",
  },
  {
    fullName: "Kahaleel Littledyke",
    gender: "Male",
    jobTitle: "Professor",
    language: "Greek",
    ssn: "201-87-3026",
    money: "$795.14",
  },
  {
    fullName: "Catarina Ketton",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Finnish",
    ssn: "651-64-7681",
    money: "$455.30",
  },
  {
    fullName: "Florinda Tissier",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Filipino",
    ssn: "763-36-5905",
    money: "$684.22",
  },
  {
    fullName: "Danyette Spridgeon",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Azeri",
    ssn: "491-20-2537",
    money: "$902.65",
  },
  {
    fullName: "Caro Peebles",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Kazakh",
    ssn: "464-72-5523",
    money: "$76.69",
  },
  {
    fullName: "Thorsten Ripping",
    gender: "Male",
    jobTitle: "Database Administrator IV",
    language: "Amharic",
    ssn: "503-17-6960",
    money: "$634.16",
  },
  {
    fullName: "Hazel Beggini",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Swahili",
    ssn: "727-49-7472",
    money: "$463.09",
  },
  {
    fullName: "Ryon Bailes",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Maltese",
    ssn: "340-19-2724",
    money: "$69.09",
  },
  {
    fullName: "Ibby Mayell",
    gender: "Female",
    jobTitle: "Compensation Analyst",
    language: "Punjabi",
    ssn: "262-37-9561",
    money: "$823.87",
  },
  {
    fullName: "Case Stiger",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Marathi",
    ssn: "199-91-7403",
    money: "$568.12",
  },
  {
    fullName: "Georgena Rosenfelt",
    gender: "Female",
    jobTitle: "Design Engineer",
    language: "Lao",
    ssn: "781-75-8800",
    money: "$907.54",
  },
  {
    fullName: "Milicent Claire",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Malayalam",
    ssn: "811-48-1514",
    money: "$657.84",
  },
  {
    fullName: "Filbert Castenda",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Tswana",
    ssn: "165-29-6210",
    money: "$876.70",
  },
  {
    fullName: "Byrom Deinert",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Dzongkha",
    ssn: "168-31-8067",
    money: "$712.83",
  },
  {
    fullName: "Aline Mailey",
    gender: "Female",
    jobTitle: "Administrative Assistant I",
    language: "Kurdish",
    ssn: "379-83-0455",
    money: "$981.63",
  },
  {
    fullName: "Vivianna Farnish",
    gender: "Female",
    jobTitle: "Nurse",
    language: "Malayalam",
    ssn: "475-52-6535",
    money: "$499.15",
  },
  {
    fullName: "Emmy Geeraert",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Tswana",
    ssn: "543-63-4045",
    money: "$748.67",
  },
  {
    fullName: "Baldwin Fuzzey",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Thai",
    ssn: "631-59-1646",
    money: "$45.89",
  },
  {
    fullName: "Barby Bangle",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Kannada",
    ssn: "432-63-5314",
    money: "$45.71",
  },
  {
    fullName: "Morgen Kenwrick",
    gender: "Male",
    jobTitle: "Marketing Manager",
    language: "Chinese",
    ssn: "186-88-8691",
    money: "$754.24",
  },
  {
    fullName: "Nelly Arnowicz",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Telugu",
    ssn: "196-44-8604",
    money: "$273.28",
  },
  {
    fullName: "Christiano Fairbourn",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "German",
    ssn: "560-88-4163",
    money: "$3.89",
  },
  {
    fullName: "Zabrina Lacase",
    gender: "Female",
    jobTitle: "Biostatistician IV",
    language: "Sotho",
    ssn: "177-61-4788",
    money: "$891.22",
  },
  {
    fullName: "Pamelina Bucke",
    gender: "Female",
    jobTitle: "Research Nurse",
    language: "Spanish",
    ssn: "651-45-5539",
    money: "$210.40",
  },
  {
    fullName: "Lian Bristowe",
    gender: "Female",
    jobTitle: "Geologist II",
    language: "Tamil",
    ssn: "447-44-1221",
    money: "$494.00",
  },
  {
    fullName: "Moore Deegin",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Swahili",
    ssn: "137-01-3984",
    money: "$36.95",
  },
  {
    fullName: "Louis Paolicchi",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Tsonga",
    ssn: "135-32-6185",
    money: "$163.28",
  },
  {
    fullName: "Justen Varnes",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Zulu",
    ssn: "762-25-2064",
    money: "$343.06",
  },
  {
    fullName: "Felita Colthurst",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Tsonga",
    ssn: "433-83-6752",
    money: "$5.84",
  },
  {
    fullName: "Whitney Beagen",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Kannada",
    ssn: "573-33-0685",
    money: "$763.15",
  },
  {
    fullName: "Chloe Collelton",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Macedonian",
    ssn: "280-91-7222",
    money: "$441.58",
  },
  {
    fullName: "Dion Kernocke",
    gender: "Male",
    jobTitle: "Editor",
    language: "Fijian",
    ssn: "186-11-2280",
    money: "$146.82",
  },
  {
    fullName: "Henrietta McGreay",
    gender: "Female",
    jobTitle: "Office Assistant IV",
    language: "Sotho",
    ssn: "650-03-6768",
    money: "$354.81",
  },
  {
    fullName: "Millie Charkham",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Fijian",
    ssn: "167-57-4682",
    money: "$53.86",
  },
  {
    fullName: "Linoel Cantera",
    gender: "Male",
    jobTitle: "Human Resources Assistant II",
    language: "German",
    ssn: "104-95-8829",
    money: "$787.81",
  },
  {
    fullName: "Elonore Sheriff",
    gender: "Female",
    jobTitle: "Programmer II",
    language: "West Frisian",
    ssn: "283-49-9205",
    money: "$886.22",
  },
  {
    fullName: "Janean Leppington",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Armenian",
    ssn: "210-97-1159",
    money: "$907.49",
  },
  {
    fullName: "Bentley Elliot",
    gender: "Male",
    jobTitle: "Programmer III",
    language: "Zulu",
    ssn: "159-14-4973",
    money: "$366.63",
  },
  {
    fullName: "Vinny Bramley",
    gender: "Male",
    jobTitle: "Media Manager I",
    language: "Malay",
    ssn: "404-08-2510",
    money: "$86.54",
  },
  {
    fullName: "Ozzie Barbara",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Gujarati",
    ssn: "270-07-6392",
    money: "$630.00",
  },
  {
    fullName: "Artemas Slyford",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Malayalam",
    ssn: "221-35-1823",
    money: "$205.24",
  },
  {
    fullName: "Jeno Castanares",
    gender: "Male",
    jobTitle: "Systems Administrator IV",
    language: "Italian",
    ssn: "499-02-4609",
    money: "$998.50",
  },
  {
    fullName: "Suki Emmott",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Malay",
    ssn: "342-30-7535",
    money: "$761.22",
  },
  {
    fullName: "Holden Vern",
    gender: "Male",
    jobTitle: "Programmer Analyst II",
    language: "Korean",
    ssn: "233-20-4487",
    money: "$144.45",
  },
  {
    fullName: "Emmy Dinkin",
    gender: "Male",
    jobTitle: "Automation Specialist I",
    language: "Aymara",
    ssn: "642-86-3333",
    money: "$468.61",
  },
  {
    fullName: "Johnnie Willock",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Yiddish",
    ssn: "394-56-1076",
    money: "$150.05",
  },
  {
    fullName: "Filippa Ickovits",
    gender: "Female",
    jobTitle: "Physical Therapy Assistant",
    language: "Latvian",
    ssn: "771-23-3467",
    money: "$436.94",
  },
  {
    fullName: "Norrie Durnill",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Bengali",
    ssn: "323-91-3229",
    money: "$164.18",
  },
  {
    fullName: "Amalita Clucas",
    gender: "Female",
    jobTitle: "Quality Control Specialist",
    language: "Malagasy",
    ssn: "726-13-5789",
    money: "$466.19",
  },
  {
    fullName: "Vladimir Penwell",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Marathi",
    ssn: "181-66-3590",
    money: "$206.75",
  },
  {
    fullName: "Everett Schukraft",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Tajik",
    ssn: "138-64-3518",
    money: "$575.41",
  },
  {
    fullName: "Wilbur McReath",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Armenian",
    ssn: "867-02-0983",
    money: "$719.18",
  },
  {
    fullName: "Vinnie Merring",
    gender: "Female",
    jobTitle: "Occupational Therapist",
    language: "Indonesian",
    ssn: "138-49-4083",
    money: "$163.48",
  },
  {
    fullName: "Fidela Bragger",
    gender: "Female",
    jobTitle: "Accountant IV",
    language: "Latvian",
    ssn: "133-39-2430",
    money: "$291.23",
  },
  {
    fullName: "Bernard Bereford",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Armenian",
    ssn: "774-44-9271",
    money: "$96.03",
  },
  {
    fullName: "Mathe Somes",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "Malay",
    ssn: "734-18-3655",
    money: "$598.12",
  },
  {
    fullName: "Hillard Threadgall",
    gender: "Male",
    jobTitle: "Structural Analysis Engineer",
    language: "Dhivehi",
    ssn: "428-19-1979",
    money: "$357.78",
  },
  {
    fullName: "Fonzie McWilliam",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Hebrew",
    ssn: "548-45-6106",
    money: "$763.46",
  },
  {
    fullName: "Chrissie Strond",
    gender: "Male",
    jobTitle: "Accountant II",
    language: "Punjabi",
    ssn: "410-66-3800",
    money: "$508.98",
  },
  {
    fullName: "Donn Truman",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Zulu",
    ssn: "155-66-6976",
    money: "$746.41",
  },
  {
    fullName: "Ivy Davisson",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Papiamento",
    ssn: "878-54-0263",
    money: "$432.06",
  },
  {
    fullName: "Hedda Fortin",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Macedonian",
    ssn: "377-08-8905",
    money: "$148.63",
  },
  {
    fullName: "Penny Fursland",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Tsonga",
    ssn: "887-47-6165",
    money: "$451.57",
  },
  {
    fullName: "Marco Goulborn",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Malay",
    ssn: "252-15-4608",
    money: "$566.50",
  },
  {
    fullName: "Raynard Gronw",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst III",
    language: "Filipino",
    ssn: "333-91-3552",
    money: "$392.72",
  },
  {
    fullName: "Cilka Braunter",
    gender: "Female",
    jobTitle: "Nurse",
    language: "Latvian",
    ssn: "290-33-6857",
    money: "$605.93",
  },
  {
    fullName: "Hannah Bumford",
    gender: "Female",
    jobTitle: "Editor",
    language: "Hiri Motu",
    ssn: "839-07-9061",
    money: "$562.07",
  },
  {
    fullName: "Thomasa Waggitt",
    gender: "Female",
    jobTitle: "Software Engineer II",
    language: "Punjabi",
    ssn: "326-90-8289",
    money: "$5.37",
  },
  {
    fullName: "Ann Shaughnessy",
    gender: "Female",
    jobTitle: "Web Designer II",
    language: "Georgian",
    ssn: "303-36-7667",
    money: "$661.61",
  },
  {
    fullName: "Thorpe Jantzen",
    gender: "Male",
    jobTitle: "Project Manager",
    language: "Kyrgyz",
    ssn: "272-20-5447",
    money: "$823.00",
  },
  {
    fullName: "Hanni Orgill",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Fijian",
    ssn: "289-54-9873",
    money: "$481.72",
  },
  {
    fullName: "Johny Lewcock",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Punjabi",
    ssn: "854-37-4954",
    money: "$662.69",
  },
  {
    fullName: "Jordan Banisch",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "Malay",
    ssn: "432-45-5532",
    money: "$219.34",
  },
  {
    fullName: "Yvor Doge",
    gender: "Male",
    jobTitle: "Staff Accountant I",
    language: "Catalan",
    ssn: "364-22-1081",
    money: "$990.80",
  },
  {
    fullName: "Neron Gomes",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Chinese",
    ssn: "444-20-9275",
    money: "$266.10",
  },
  {
    fullName: "Alair Abdie",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Nepali",
    ssn: "529-36-0731",
    money: "$595.09",
  },
  {
    fullName: "Eda Arnaud",
    gender: "Female",
    jobTitle: "Engineer IV",
    language: "Punjabi",
    ssn: "878-37-5855",
    money: "$803.56",
  },
  {
    fullName: "Carlene Welland",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Malagasy",
    ssn: "246-52-7310",
    money: "$162.94",
  },
  {
    fullName: "Noah Donegan",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "Sotho",
    ssn: "245-20-8342",
    money: "$661.49",
  },
  {
    fullName: "Jesselyn Denyukhin",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Belarusian",
    ssn: "498-25-8165",
    money: "$92.39",
  },
  {
    fullName: "Melony Kleeborn",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Assamese",
    ssn: "163-37-6620",
    money: "$160.50",
  },
  {
    fullName: "Quintus Spon",
    gender: "Male",
    jobTitle: "Operator",
    language: "Persian",
    ssn: "138-51-1367",
    money: "$253.54",
  },
  {
    fullName: "Alexandros Mingame",
    gender: "Male",
    jobTitle: "Cost Accountant",
    language: "Assamese",
    ssn: "384-24-3205",
    money: "$901.62",
  },
  {
    fullName: "Oran Samett",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Persian",
    ssn: "158-07-5472",
    money: "$628.09",
  },
  {
    fullName: "Sammy Bourges",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Bengali",
    ssn: "299-79-7103",
    money: "$509.93",
  },
  {
    fullName: "Kathlin Merigot",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Zulu",
    ssn: "465-59-9089",
    money: "$845.45",
  },
  {
    fullName: "Georges Gianullo",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Tetum",
    ssn: "721-20-6049",
    money: "$376.08",
  },
  {
    fullName: "Rozelle Do Rosario",
    gender: "Female",
    jobTitle: "Programmer I",
    language: "Hiri Motu",
    ssn: "516-05-5974",
    money: "$448.05",
  },
  {
    fullName: "Doy Dafforne",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Macedonian",
    ssn: "792-31-4404",
    money: "$682.51",
  },
  {
    fullName: "De Piecha",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Croatian",
    ssn: "701-61-4593",
    money: "$259.45",
  },
  {
    fullName: "Kirbie Ascraft",
    gender: "Female",
    jobTitle: "Editor",
    language: "Haitian Creole",
    ssn: "669-28-9709",
    money: "$960.16",
  },
  {
    fullName: "Pablo Fardon",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Filipino",
    ssn: "870-38-1892",
    money: "$649.01",
  },
  {
    fullName: "Sanderson Cathery",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Bosnian",
    ssn: "710-55-9240",
    money: "$98.44",
  },
  {
    fullName: "Bennett Merrington",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Albanian",
    ssn: "768-47-9528",
    money: "$957.58",
  },
  {
    fullName: "Sim Larraway",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Lithuanian",
    ssn: "847-76-4976",
    money: "$994.45",
  },
  {
    fullName: "Christye Gaskamp",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Haitian Creole",
    ssn: "648-08-7132",
    money: "$329.11",
  },
  {
    fullName: "Hally Soro",
    gender: "Female",
    jobTitle: "Account Coordinator",
    language: "Albanian",
    ssn: "837-72-0836",
    money: "$646.77",
  },
  {
    fullName: "Nessie Fowley",
    gender: "Female",
    jobTitle: "Human Resources Assistant II",
    language: "Oriya",
    ssn: "613-90-5437",
    money: "$435.50",
  },
  {
    fullName: "Alexandre Hastewell",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Korean",
    ssn: "200-90-2404",
    money: "$728.86",
  },
  {
    fullName: "Laureen Ezzell",
    gender: "Female",
    jobTitle: "Human Resources Assistant II",
    language: "Moldovan",
    ssn: "484-86-8941",
    money: "$591.43",
  },
  {
    fullName: "Gabriel Scudamore",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Tamil",
    ssn: "403-43-4041",
    money: "$18.10",
  },
  {
    fullName: "Riobard Saice",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Italian",
    ssn: "276-72-1612",
    money: "$760.96",
  },
  {
    fullName: "Berthe Ahearne",
    gender: "Female",
    jobTitle: "Computer Systems Analyst IV",
    language: "Marathi",
    ssn: "129-40-0316",
    money: "$410.07",
  },
  {
    fullName: "Erina Trillow",
    gender: "Female",
    jobTitle: "Human Resources Manager",
    language: "Malay",
    ssn: "350-54-1189",
    money: "$137.49",
  },
  {
    fullName: "Lawry Coddrington",
    gender: "Male",
    jobTitle: "Actuary",
    language: "Khmer",
    ssn: "866-24-5933",
    money: "$469.66",
  },
  {
    fullName: "Freddie Billie",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Luxembourgish",
    ssn: "284-45-2290",
    money: "$317.46",
  },
  {
    fullName: "Dede Hanscom",
    gender: "Female",
    jobTitle: "Sales Representative",
    language: "Punjabi",
    ssn: "402-54-0089",
    money: "$955.65",
  },
  {
    fullName: "Cordy Able",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Zulu",
    ssn: "347-94-5104",
    money: "$102.31",
  },
  {
    fullName: "Krista Seabourne",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Somali",
    ssn: "337-39-8201",
    money: "$211.40",
  },
  {
    fullName: "Melisandra Cassam",
    gender: "Female",
    jobTitle: "Social Worker",
    language: "Oriya",
    ssn: "163-44-2564",
    money: "$509.50",
  },
  {
    fullName: "Anna-diane Lindstrom",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Quechua",
    ssn: "136-11-2696",
    money: "$656.85",
  },
  {
    fullName: "Elinore Rihosek",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Mongolian",
    ssn: "115-79-0260",
    money: "$941.11",
  },
  {
    fullName: "Hillel Kellar",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "French",
    ssn: "284-64-6935",
    money: "$371.28",
  },
  {
    fullName: "Chancey Kiossel",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Kannada",
    ssn: "744-50-5260",
    money: "$452.88",
  },
  {
    fullName: "Ario McJarrow",
    gender: "Male",
    jobTitle: "Database Administrator I",
    language: "Moldovan",
    ssn: "278-62-9621",
    money: "$32.13",
  },
  {
    fullName: "Any Lanchester",
    gender: "Male",
    jobTitle: "Professor",
    language: "Persian",
    ssn: "667-24-0140",
    money: "$72.69",
  },
  {
    fullName: "Alaric Durber",
    gender: "Male",
    jobTitle: "Administrative Assistant III",
    language: "Māori",
    ssn: "869-77-4469",
    money: "$732.46",
  },
  {
    fullName: "Clemmie Heasly",
    gender: "Female",
    jobTitle: "Financial Advisor",
    language: "Bosnian",
    ssn: "218-53-1256",
    money: "$46.39",
  },
  {
    fullName: "Curr Bertomeu",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Punjabi",
    ssn: "359-66-3714",
    money: "$691.91",
  },
  {
    fullName: "Birch Fores",
    gender: "Male",
    jobTitle: "General Manager",
    language: "Estonian",
    ssn: "660-45-6833",
    money: "$686.40",
  },
  {
    fullName: "Flossi Bramham",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Hebrew",
    ssn: "319-01-9541",
    money: "$979.38",
  },
  {
    fullName: "Adelle Bengochea",
    gender: "Female",
    jobTitle: "Senior Cost Accountant",
    language: "Kannada",
    ssn: "210-22-3296",
    money: "$252.82",
  },
  {
    fullName: "Jephthah Dunlap",
    gender: "Male",
    jobTitle: "Project Manager",
    language: "Irish Gaelic",
    ssn: "542-97-4562",
    money: "$380.26",
  },
  {
    fullName: "Carmina Gorick",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Czech",
    ssn: "244-08-5283",
    money: "$495.18",
  },
  {
    fullName: "Tamas Garatty",
    gender: "Male",
    jobTitle: "Assistant Media Planner",
    language: "Burmese",
    ssn: "522-88-6755",
    money: "$768.12",
  },
  {
    fullName: "Leontine MacKeever",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Finnish",
    ssn: "863-60-9425",
    money: "$257.01",
  },
  {
    fullName: "Anica Dilawey",
    gender: "Female",
    jobTitle: "Social Worker",
    language: "Dzongkha",
    ssn: "363-12-6336",
    money: "$10.26",
  },
  {
    fullName: "Saunderson Coon",
    gender: "Male",
    jobTitle: "Developer III",
    language: "Icelandic",
    ssn: "578-53-3448",
    money: "$245.56",
  },
  {
    fullName: "Tilly Dommersen",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "Armenian",
    ssn: "363-09-0841",
    money: "$302.75",
  },
  {
    fullName: "Chris Matantsev",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Portuguese",
    ssn: "271-70-8394",
    money: "$312.56",
  },
  {
    fullName: "Mozelle Spennock",
    gender: "Female",
    jobTitle: "Engineer III",
    language: "Croatian",
    ssn: "710-10-6126",
    money: "$623.98",
  },
  {
    fullName: "Jude Bus",
    gender: "Male",
    jobTitle: "Systems Administrator III",
    language: "Tamil",
    ssn: "157-12-7666",
    money: "$632.89",
  },
  {
    fullName: "Sisile Sayse",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Māori",
    ssn: "136-83-1289",
    money: "$511.51",
  },
  {
    fullName: "Putnem Feasey",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Hungarian",
    ssn: "772-03-9921",
    money: "$928.06",
  },
  {
    fullName: "Melba Poate",
    gender: "Female",
    jobTitle: "Human Resources Manager",
    language: "Bengali",
    ssn: "104-18-7516",
    money: "$623.15",
  },
  {
    fullName: "Elie Madden",
    gender: "Female",
    jobTitle: "VP Quality Control",
    language: "Afrikaans",
    ssn: "628-78-5809",
    money: "$684.18",
  },
  {
    fullName: "Eli Ockendon",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Finnish",
    ssn: "723-25-7182",
    money: "$606.49",
  },
  {
    fullName: "Atlanta Blakes",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Latvian",
    ssn: "245-92-7144",
    money: "$582.09",
  },
  {
    fullName: "Brian Gear",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Malayalam",
    ssn: "516-96-9865",
    money: "$879.94",
  },
  {
    fullName: "Kath Gagg",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Kyrgyz",
    ssn: "842-46-4574",
    money: "$236.01",
  },
  {
    fullName: "Sigfried McMackin",
    gender: "Male",
    jobTitle: "Statistician IV",
    language: "Pashto",
    ssn: "147-54-9666",
    money: "$241.94",
  },
  {
    fullName: "Isac Hartill",
    gender: "Male",
    jobTitle: "Recruiter",
    language: "Amharic",
    ssn: "642-33-7597",
    money: "$10.26",
  },
  {
    fullName: "Bealle Mowday",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Dhivehi",
    ssn: "323-54-6096",
    money: "$318.00",
  },
  {
    fullName: "Gianna Polotti",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "French",
    ssn: "880-20-7865",
    money: "$626.69",
  },
  {
    fullName: "Hartley Helleckas",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst I",
    language: "Indonesian",
    ssn: "554-04-5475",
    money: "$208.10",
  },
  {
    fullName: "Florella Goby",
    gender: "Female",
    jobTitle: "Nuclear Power Engineer",
    language: "Catalan",
    ssn: "685-26-9085",
    money: "$838.30",
  },
  {
    fullName: "Blaine Norwell",
    gender: "Male",
    jobTitle: "Programmer I",
    language: "West Frisian",
    ssn: "751-31-5054",
    money: "$739.64",
  },
  {
    fullName: "Junina Jillions",
    gender: "Female",
    jobTitle: "Help Desk Operator",
    language: "Chinese",
    ssn: "849-99-3600",
    money: "$398.59",
  },
  {
    fullName: "Dani Cours",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Lao",
    ssn: "803-29-5820",
    money: "$634.55",
  },
  {
    fullName: "Lacee Snedker",
    gender: "Female",
    jobTitle: "Programmer IV",
    language: "Chinese",
    ssn: "414-90-3077",
    money: "$932.35",
  },
  {
    fullName: "Jami Lunt",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst II",
    language: "Gagauz",
    ssn: "623-37-7855",
    money: "$605.88",
  },
];

// 1. 성별이 남성이고 직업(jobTitle)이 Engineer가 포함된 사람들만 나타내기

const q1 = data.filter(
  (x) => x.gender == "Male" && x.jobTitle.includes("Engineer")
);

console.log(q1);

// 2. 이름에서 성(가족이름)을 없애고, ssn을 하이픈 없애고, money를 달러에서 원화로 환율 적용시킨 후 나타내기

const q2 = data.map((x) => {
  x.fullName = x.fullName.split(" ")[0];
  x.ssn = x.ssn.split("-").reduce((a, c) => a + c);
  x.money = +x.money.slice(1, x.money.length) * 1500;
  return x;
});

console.log(q2);
